[package]
name = "wsc-network"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
wsc-consensus = { path = "../wsc-consensus" }
wsc-core = { path = "../wsc-core" }
wsc-crypto = { path = "../wsc-crypto" }
wsc-node = { path = "../wsc-node" }
