[package]
name = "wsc-bridge"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
reqwest = { version = "=0.11.27", default-features = false, features = ["json", "rustls-tls"] }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
url.workspace = true
wsc-core = { path = "../wsc-core" }
